#
# General comments:
#
# 1. Currently no platform tests the documentation generation with doxygen.
#    The reasons are that generation takes a long time and I am not confident
#    which Ubuntu package are necessary (I use Fedora for development). 
#    The long time it takes to run, makes CI for doxygen impractical.
#    I left the necessary statements commented out in the "packages" section
#    of the CLANG platform.
# 2. We have no test for a platform without ncurses because it is unclear which
#    library would replace ncurses. Would it be termlib or termcap or something else?
#    See issue #85: Travis CI does not include platform without ncurses.
#

language: c

matrix:
  include:
    # GCC - works on Ubuntu Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libncurses5-dev
            - check
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libncurses5-dev
            - check
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
         
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libncurses5-dev
            - check
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
 
    # CLANG - works on Ubuntu Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - check
#            Excluded due to excessive execution times and uncertainty
#            which other packages are necessary. Installing doxygen triggers
#            the documentation generation.
#            - doxygen
#            - doxygen-latex
#            - texlive
#            - texlive-latex-base
#            - texlive-latex-extra
#            - texlive-latex-recommended
#            - texlive-pictures
#            - graphviz
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
    
    # OS X --- DOES NOT WORK
#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - autoconf --version
  - sudo apt-get -qq update
#  - sudo apt-get install -y gcc
#  - sudo apt-get install libncurses5-dev
  
script:
  - autoreconf -ivf
  - mkdir -p build
  - cd build
  - ../configure
  - make
  - sudo make install
  - make check
  - make clean
