#
# General comments:
#
# 1. We test doxygen only on one platform as there is no platform depency change
#    relevant to doxygen. We test it on the clang platform. Maybe we should not
#    integration test the documentation at all. to be decided later.

language: c

matrix:
  include:
    # GCC - works on Ubuntu Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libncurses5-dev
            - check
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libncurses5-dev
            - check
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
         
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libncurses5-dev
            - check
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        
    # CLANG - works on Ubuntu Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - check
            - doxygen
            - doxygen-latex
            - texlive
            - texlive-latex-extra
            - graphviz
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
    
    # OS X --- DOES NOT WORK
#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - autoconf --version
  - sudo apt-get -qq update
#  - sudo apt-get install -y gcc
#  - sudo apt-get install libncurses5-dev
#  - sudo apt-get install -y check
  
script:
  - autoreconf -ivf
  - mkdir -p build
  - cd build
  - ../configure
  - make
  - sudo make install
  - make check
  - make clean
